### ISSUE TITLE
Does not handle silent 'es' correctly

### ISSUE THREAD

**Issue by zteater** [m09/syllable-counter#30]
I've noticed regular 'es' are calculated correctly
cheese = 1
cheeses = 2

However, the silent 'es' seems to return wrong values
bike = 1
bikes = 2 (expecting 1)

**Comment by m09** [comment]
Hi Zack, sorry for the late reply I completely missed this issue. Please don't hesitate to let me know if you've found a workaround. If not I'll try to investigate when I have some free time.

**Comment by Gerudhoh** [comment]
It also thinks false has 2 syllables

**Comment by zteater** [comment]
@m09 I don't think the issue is necessarily with the way this is coded. It seems to be more of an issue with the syllable algorithm, as a whole.

**Comment by raining211** [comment]
Hi, thanks for sharing your products.
I'm trying to use your 'syllable counter' in my android project. But I've had no luck.
I added the line below in my gradle dependencies.
implementation files('libs/syllable-counter-4.1.0.jar')

When I run my app, 'NoSuchMethodError' comes from SyllableCounter.
Do you have any ideas what went wrong, or do you happen to know anyone who has used SyllableCounter in their android projects?
Thanks in advance.

**Comment by m09** [comment]
Yup I meant if you had a pattern in mind to add to the current list. Anyway, closing for now. I'll add a way to add exceptions at runtime when I get a chance so that users can enhance the list easily when they notice an error.
