### ISSUE TITLE
"Saying" and some other -ing words do not count correctly

### ISSUE THREAD

**Issue by Nincodedo** [m09/syllable-counter#32]
"Saying" comes back as 1 syllable even though it's 2. I have made a fix [here](https://github.com/Nincodedo/syllable-counter/commit/ee9a375a6a7f925cab187c4d31f01e6d7745dac2). Would you be open to accepting a PR?

**Comment by m09** [comment]
Hi @Nincodedo, sure I'll merge improvements! Thanks for taking the time to fix the issue :fire:

**Comment by m09** [comment]
Thanks for the PR @Nincodedo, 4.1.0 has been push to Maven Central :smile_cat:

**Comment by Nincodedo** [comment]
Awesome. Thank you for the quick response!
