### ISSUE TITLE
List of syllables

### ISSUE THREAD

**Issue by lodenrogue** [m09/syllable-counter#35]
Any way to get a list of the syllables in a given string?

Example

Input: "Hello"
Output: ["Hel", "lo"]

**Comment by m09** [comment]
Hi @lodenrogue,

This basic algorithm won't cut it to provide the strings of syllables. I have another repo where I do syllable stuff with neural network that might be able to do that. I haven't touched it in a long time but will come back to it and keep you posted if I reach a satisfying point.

For reference the repo is m09/charybde.
